import {Dimensions, StyleSheet} from 'react-native';
const {height} = Dimensions.get('window');
export default StyleSheet.create({
  keyboardAware: {flex: 1},
  container: {flex: 1, height, marginHorizontal: 10},
  viewNotification: {
    marginVertical: 10,
    flexDirection: 'row',
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
  },
  viewImageList: {
    flex: 0.15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  viewMessage: {
    flex: 0.15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iMessage: {height: '50%', width: '50%'},
  Notification: {
    flex: 0.7,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  imageLocation: {height: 18, width: 15},
  textNotification: {fontSize: 20},
  textExplore: {fontWeight: 'bold', fontSize: 36, marginVertical: 5},
  textBest: {fontSize: 26, opacity: 0.4},
  viewSearch: {
    marginVertical: 10,
    flexDirection: 'row',
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
    backgroundColor: 'white',
  },
  viewTextSearch: {
    flex: 0.7,
    flexDirection: 'row',
    alignItems: 'center',
  },
  imageViewSearch: {
    height: '100%',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
  },
  imageSearch: {tintColor: 'black', height: '40%', width: '40%'},
  view1: {
    width: '100%',
    height: 120,
    backgroundColor: 'white',
    borderRadius: 15,
  },
  viewNewSee: {
    height: 30,
    width: '100%',
    flexDirection: 'row',
    marginVertical: 10,
    marginTop: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  viewNew: {flex: 0.8},
  textNew: {fontSize: 24, fontWeight: 'bold'},
  viewSee: {flex: 0.2},
  textSee: {
    fontSize: 24,
    opacity: 0.5,
  },
  view2: {
    width: '100%',
    height: 220,
    backgroundColor: 'white',
    borderRadius: 15,
  },
  view3: {
    flexDirection: 'row',
    marginTop: 20,
    width: '100%',
    height: 100,
    borderRadius: 15,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
  },
  view31: {
    flex: 0.25,
    height: 100,
    borderRadius: 15,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
  },
  heart: {
    height: '25%',
    width: '25%',
  },
  person: {
    height: '23%',
    width: '23%',
  },
  image30: {tintColor: '#ff8c00'},
  image31: {},
  text30: {marginTop: 5, color: '#ff8c00'},
  text31: {marginTop: 5},
});
